package enumerations;

public enum AgeGroup {

	NINETEEN_TO_TWENTY_FOUR,
	TWENTY_FIVE_TO_TWENTY_NINE,
	THIRTY_TO_THIRTY_FOUR,
	THIRTY_FIVE_TO_THIRTY_NINE,
	FORTY_TO_FORTY_FOUR,
	FORTY_FIVE_TO_FORTY_NINE,
	FIFTY_TO_FIFTY_FOUR,
	FIFTY_FIVE_TO_FIFTY_NINE,
	SIXTY_TO_SIXTY_FOUR,
	SIXTY_FIVE_TO_SIXTY_NINE,
	SEVENTY_TO_SEVENTY_FOUR,
	SEVENTY_FIVE_TO_SEVENTY_NINE,
	EIGHTY_TO_EIGHTY_FOUR,
	EIGHTY_FIVE_TO_EIGHTY_NINE,
	NINETY_TO_NINETY_FOUR,
	NINETY_FIVE_TO_NINETY_NINE,
	ONE_HUNDRE_TO_ONE_HUNDRED_AND_FOUR,
	ONE_HUNDRED_AND_FIVE_TO_ONE_HUNDRED_AND_NINE,
	ONE_HUNDRED_TEN_TO_ONE_HUNDRED_FOURTEEN,
	OVER_ONE_HUNDRED_FIFTEEN;

}